# Generated by Django 5.2.4 on 2025-07-11 02:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name (minimum 2 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='PredefinedStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('structure_type', models.CharField(choices=[('motion_graphics', 'Motion Graphics'), ('graphic_design', 'Graphic Design (Poster/Flyer)'), ('web_development', 'Web Development'), ('video_editing', 'Video Editing'), ('photography', 'Photography'), ('custom', 'Custom')], max_length=20)),
                ('structure_data', models.JSONField(help_text='JSON representation of the folder structure')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='Make this structure available to all users')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['structure_type', 'name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name (minimum 2 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('save_location', models.CharField(default='\\\\192.168.29.136\\EFX_Projects\\clients', help_text='Base directory where project folders will be created', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'client')},
            },
        ),
        migrations.CreateModel(
            name='FolderStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Structure', max_length=100)),
                ('structure_data', models.JSONField(help_text='JSON representation of the folder structure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_created', models.BooleanField(default=False, help_text='Whether folders have been physically created')),
                ('created_path', models.CharField(blank=True, help_text='Actual path where folders were created', max_length=500, null=True)),
                ('predefined_structure', models.ForeignKey(blank=True, help_text='Reference to predefined structure if used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.predefinedstructure')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_structures', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
